### PR TITLE
Add aser_agent attribute to all API calls

### PR DESCRIPTION
**Pull request by JanC89**

### CODE REVIEW

**Comment by anderswb** [comment]
Instead of adding VERSION = "1.1.1" to the Pykkelabels class, the version should be fetched from the __version__ variable in pykkelabels/__init__.py.

This is the version number used by pypi, and having to change the version number more than one place seems tedious.

**Comment by JanC89** [comment]
Good point. 

However, I don't know enough about Python to do this in the correct way.

But, I guess there is somewhat recommended/de facto way of doing it?

**Comment by anderswb** [comment]
I'm not quite sure. It's possible that we need to move the version infomation into a separate file. I'll look into it later.

**Comment by anderswb** [comment]
I've moved the relevant stuff into version.py. This makes it easier to reference the variables from other places.

**Pull request merged**
